"use strict";
const bcrypt = require("bcrypt");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("Users", [
      {
        nombre: "Eric",
        apellidos: "Lara",
        contrasena: await bcrypt.hash("123456", 10),
        correo: "ericlaravega@gmail.com",
        movil: "123-456-7890",
        idEscuela: 1,
        idRol: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nombre: "Claudio",
        apellidos: "Fuentes",
        contrasena: await bcrypt.hash("123456", 10),
        correo: "claudio20fuentes@gmail.com",
        movil: "123-456-7890",
        idEscuela: 1,
        idRol: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nombre: "Sara",
        apellidos: "Rojas",
        contrasena: await bcrypt.hash("123456", 10),
        correo: "profesor_guia@example.com",
        movil: "123-456-7890",
        idEscuela: 1,
        idRol: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nombre: "Pablo",
        apellidos: "Sepúlveda",
        contrasena: await bcrypt.hash("123456", 10),
        correo: "profesor_asignatura@example.com",
        movil: "987-654-3210",
        idEscuela: 1,
        idRol: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nombre: "Pedro",
        apellidos: "Herrera",
        contrasena: await bcrypt.hash("123456", 10),
        correo: "apoderado@example.com",
        movil: "987-654-3210",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 6
      {
        nombre: "Francisca",
        apellidos: "Pérez",
        contrasena: await bcrypt.hash("yabbadabbadoo", 10),
        correo: "fred.flintstone@example.com",
        movil: "555-123-4567",
        idEscuela: 1,
        idRol: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 7
      {
        nombre: "Alejandro",
        apellidos: "Torres",
        contrasena: await bcrypt.hash("rockstar123", 10),
        correo: "barney.rubble@example.com",
        movil: "555-987-6543",
        idEscuela: 1,
        idRol: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 8
      {
        nombre: "Wilma",
        apellidos: "Flores",
        contrasena: await bcrypt.hash("wilma123", 10),
        correo: "wilma.flintstone@example.com",
        movil: "555-234-5678",
        idEscuela: 1,
        idRol: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 9
      {
        nombre: "Beatriz",
        apellidos: "Cáceres",
        contrasena: await bcrypt.hash("bettyrocks", 10),
        correo: "betty.rubble@example.com",
        movil: "555-789-1234",
        idEscuela: 1,
        idRol: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 10
      {
        nombre: "Amaya",
        apellidos: "Toledo",
        contrasena: await bcrypt.hash("babyrocks", 10),
        correo: "pebbles.flintstone@example.com",
        movil: "555-345-6789",
        idEscuela: 1,
        idRol: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 11
      {
        nombre: "Carlos",
        apellidos: "González",
        contrasena: await bcrypt.hash("carlos123", 10),
        correo: "carlos.gonzalez@example.com",
        movil: "555-111-2222",
        idEscuela: 1,
        idRol: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 12
      {
        nombre: "María",
        apellidos: "López",
        contrasena: await bcrypt.hash("maria456", 10),
        correo: "maria.lopez@example.com",
        movil: "555-333-4444",
        idEscuela: 1,
        idRol: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 13
      {
        nombre: "Javier",
        apellidos: "Ramírez",
        contrasena: await bcrypt.hash("javier789", 10),
        correo: "javier.ramirez@example.com",
        movil: "555-555-6666",
        idEscuela: 1,
        idRol: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 14
      {
        nombre: "Isabel",
        apellidos: "Martínez",
        contrasena: await bcrypt.hash("isabel101", 10),
        correo: "isabel.martinez@example.com",
        movil: "555-777-8888",
        idEscuela: 1,
        idRol: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 15
      {
        nombre: "Alejandro",
        apellidos: "Pérez",
        contrasena: await bcrypt.hash("alejandro202", 10),
        correo: "alejandro.perez@example.com",
        movil: "555-999-0000",
        idEscuela: 1,
        idRol: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //id 16
      {
        nombre: "Andrés",
        apellidos: "Lagos",
        contrasena: await bcrypt.hash("andres123", 10),
        correo: "andres.lagos@example.com",
        movil: "555-111-2222",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Isidora",
        apellidos: "García",
        contrasena: await bcrypt.hash("isidora456", 10),
        correo: "isidora.garcia@example.com",
        movil: "555-333-4444",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Manuel",
        apellidos: "Soto",
        contrasena: await bcrypt.hash("manuel789", 10),
        correo: "manuel.soto@example.com",
        movil: "555-555-6666",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Fernanda",
        apellidos: "Molina",
        contrasena: await bcrypt.hash("fernanda101", 10),
        correo: "fernanda.molina@example.com",
        movil: "555-777-8888",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Ricardo",
        apellidos: "Valdés",
        contrasena: await bcrypt.hash("ricardo202", 10),
        correo: "ricardo.valdes@example.com",
        movil: "555-999-0000",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Daniela",
        apellidos: "Fuentes",
        contrasena: await bcrypt.hash("daniela123", 10),
        correo: "daniela.fuentes@example.com",
        movil: "555-111-2222",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Eduardo",
        apellidos: "Hernández",
        contrasena: await bcrypt.hash("eduardo456", 10),
        correo: "eduardo.hernandez@example.com",
        movil: "555-333-4444",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Valentina",
        apellidos: "Silva",
        contrasena: await bcrypt.hash("valentina789", 10),
        correo: "valentina.silva@example.com",
        movil: "555-555-6666",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Felipe",
        apellidos: "Gómez",
        contrasena: await bcrypt.hash("felipe101", 10),
        correo: "felipe.gomez@example.com",
        movil: "555-777-8888",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Camila",
        apellidos: "Rojas",
        contrasena: await bcrypt.hash("camila202", 10),
        correo: "camila.rojas@example.com",
        movil: "555-999-0000",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nombre: "Antonio",
        apellidos: "López",
        contrasena: await bcrypt.hash("antonio123", 10),
        correo: "antonio.lopez@example.com",
        movil: "555-111-2222",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Valeria",
        apellidos: "González",
        contrasena: await bcrypt.hash("valeria456", 10),
        correo: "valeria.gonzalez@example.com",
        movil: "555-333-4444",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Luis",
        apellidos: "Torres",
        contrasena: await bcrypt.hash("luis789", 10),
        correo: "luis.torres@example.com",
        movil: "555-555-6666",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Isabella",
        apellidos: "Molina",
        contrasena: await bcrypt.hash("isabella101", 10),
        correo: "isabella.molina@example.com",
        movil: "555-777-8888",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Diego",
        apellidos: "Valenzuela",
        contrasena: await bcrypt.hash("diego202", 10),
        correo: "diego.valenzuela@example.com",
        movil: "555-999-0000",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Constanza",
        apellidos: "Soto",
        contrasena: await bcrypt.hash("constanza123", 10),
        correo: "constanza.soto@example.com",
        movil: "555-111-2222",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Felipe",
        apellidos: "Hernández",
        contrasena: await bcrypt.hash("felipe456", 10),
        correo: "felipe.hernandez@example.com",
        movil: "555-333-4444",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Gabriela",
        apellidos: "Silva",
        contrasena: await bcrypt.hash("gabriela789", 10),
        correo: "gabriela.silva@example.com",
        movil: "555-555-6666",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Roberto",
        apellidos: "Gómez",
        contrasena: await bcrypt.hash("roberto101", 10),
        correo: "roberto.gomez@example.com",
        movil: "555-777-8888",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        nombre: "Catalina",
        apellidos: "Rojas",
        contrasena: await bcrypt.hash("catalina202", 10),
        correo: "catalina.rojas@example.com",
        movil: "555-999-0000",
        idEscuela: 1,
        idRol: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Add more users as needed
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("Users", null, {});
  },
};
